runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /blog/css
  static_dir: css

- url: /blog/js
  static_dir: js

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
